"""initial schema

Revision ID: 0ff1a0f813d2
Revises: 
Create Date: 2026-07-21 11:13:43.838460
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff1a0f813d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('input_snapshot', sa.Text(), nullable=True),
    sa.Column('retrieved_sources', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('policy_checks', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('prev_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('idx_audit_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('documents',
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('storage_uri', sa.String(length=1000), nullable=True),
    sa.Column('ingestion_status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('policies',
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_definition', sa.Text(), nullable=False),
    sa.Column('risk_threshold', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('tools',
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.Text(), nullable=False),
    sa.Column('output_schema', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('endpoint', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('tool_id')
    )
    op.create_table('usage_metrics',
    sa.Column('metric_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('automation_count', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('metric_id')
    )
    with op.batch_alter_table('usage_metrics', schema=None) as batch_op:
        batch_op.create_index('uq_user_metric_date', ['user_id', 'metric_date'], unique=True)

    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('external_idp_subject', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('uq_user_subject', ['external_idp_subject'], unique=True)

    op.create_table('agent_workflows',
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('workflow_id')
    )
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.Column('doc_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('pinecone_vector_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.doc_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('idx_chunks_doc_id', ['doc_id'], unique=False)

    op.create_table('hitl_approvals',
    sa.Column('approval_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['audit_events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('conversation_turns',
    sa.Column('turn_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('entities', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turn_id')
    )
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.create_index('idx_turns_session_time', ['session_id', 'created_at'], unique=False)

    op.create_table('long_term_memory',
    sa.Column('fact_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('source_session_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.session_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.String(length=36), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('correction_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['turn_id'], ['conversation_turns.turn_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('long_term_memory')
    with op.batch_alter_table('conversation_turns', schema=None) as batch_op:
        batch_op.drop_index('idx_turns_session_time')

    op.drop_table('conversation_turns')
    op.drop_table('sessions')
    op.drop_table('hitl_approvals')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index('idx_chunks_doc_id')

    op.drop_table('document_chunks')
    op.drop_table('agent_workflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_user_subject')

    op.drop_table('users')
    with op.batch_alter_table('usage_metrics', schema=None) as batch_op:
        batch_op.drop_index('uq_user_metric_date')

    op.drop_table('usage_metrics')
    op.drop_table('tools')
    op.drop_table('policies')
    op.drop_table('documents')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user_time')

    op.drop_table('audit_events')
    # ### end Alembic commands ###
