"""
Layer 6 — Cognition Result Contract.

Defines the canonical output of the Cognition Layer (L6).
The CognitionResult encapsulates the raw generated completion output,
inference metadata (provider, tokens), confidence estimation, and 
proposed actions with side effects.

Traces to:
  - Document 10 (API Specification) Section 6: Cognition API contract
  - Document 12 (Prompt Engineering Guide) Section 3: Standard prompt outputs
  - Document 13 (Agent Design) Section 9: Explainability trace fields
  - Document 7 (LLD) Section 11: Inter-layer events (CognitionResult)
"""

from typing import Optional, List, Dict, Any
from datetime import datetime
from pydantic import Field

from axiom.core.models.base import (
    OCIFBaseModel, RequestContext, new_uuid, utc_now,
)
from axiom.core.models.orchestration import OrchestrationPlan


class ProposedAction(OCIFBaseModel):
    """
    A side-effecting tool action proposed by the agent/LLM.
    Requires validation and authorization from Layer 7 before executing.
    """
    action_id: str = Field(default_factory=new_uuid)
    action_type: str = Field(..., description="API action name or tool name (e.g., issue_refund)")
    tool_id: str = Field(..., description="ID of registered tool to execute")
    payload: Dict[str, Any] = Field(default_factory=dict, description="Arguments to be evaluated against policy rules")
    rationale: str = Field(..., description="Reasoning for proposed action")
    risk_self_assessment: str = Field(default="low", description="Agent self-assessed risk level: low | medium | high")


class TokenUsage(OCIFBaseModel):
    """Token usage tracking statistics."""
    input_tokens: int = Field(default=0)
    output_tokens: int = Field(default=0)
    cost_usd: float = Field(default=0.0)


class CognitionResult(OCIFBaseModel):
    """
    Canonical output of Layer 6 — Cognition.

    Holds inference outputs, provider-routing tracing variables, tokens usage stats,
    confidence ratings, and structural action proposals.

    Per Doc 10 Section 6 and Doc 12:
    - Standard response text (structured or unstructured)
    - Inference provider used
    - Confidence scoring (0.0-1.0)
    - Step-by-step reasoning trace logs
    - Structured action proposals
    """
    result_id: str = Field(default_factory=new_uuid, description="Unique cognition result ID")
    timestamp: datetime = Field(default_factory=utc_now)

    # Completion payload
    content: str = Field(..., description="Raw text generated by the model adapter")
    confidence: float = Field(default=0.0, description="Model-generated or calibrated confidence score (0.0-1.0)")
    reasoning_trace: str = Field(..., description="Explainable step trace log from the agent pipeline")

    # Routing tracking
    provider_used: str = Field(..., description="The LLM provider that generated the response")
    model_name_used: str = Field(..., description="Name of model weight configuration used")
    token_usage: TokenUsage = Field(default_factory=TokenUsage)

    # Proposed side-effecting actions (gated for L7 analysis)
    proposed_actions: List[ProposedAction] = Field(default_factory=list, description="Actions proposed for Layer 7 approval")

    # Upstream layers & request contexts
    orchestration_plan: OrchestrationPlan = Field(..., description="Associated agent orchestration plan details")
    request_context: RequestContext = Field(..., description="Request execution metadata envelope")
